#set( $dollar = '$' )
server:
  port: ${dollar}{port:8080}

logging:
  level:
    ${package}: DEBUG

info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
